name: Test 71080299

on:
  push:
    tags-ignore:
      - "v*"
  pull_request:
    tags-ignore:
      - "v*"

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Debug echo
        run: |
          echo "Debug"
