name: Test 71087094

on: push

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Debug echo
        run: |
          echo "::error file=./data/Sales.csv,line=1,col=1,endColumn=2,title=YOUR-TITLE::Missing semicolon" && exit 1
