name: Test 71087094

on:
  workflow_dispatch:

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
      - name: Debug echo
        run: |
          echo "::error file=data/Sales.csv,line=1,col=5,endColumn=7,title=YOUR-TITLE::Missing semicolon" && exit 1
